### ISSUE TITLE
Documentation page shows 404

### ISSUE THREAD

**Issue by hassanraza-10x** [riscv-steel/riscv-steel-core#7]
https://rafaelcalcada.github.io/steel-core/ this link for doc is not working. Please can you look into this. thanks

**Comment by rafaelcalcada** [comment]
Hi @hassanraza-10x, can you please share the URL of the page where you found this link? Thanks!

**Comment by hassanraza-10x** [comment]
> Hi @hassanraza-10x, can you please share the URL of the page where you found this link? Thanks!

https://opencores.org/projects/steelcore

**Comment by rafaelcalcada** [comment]
Thanks for pointing this out. The docs page changed to https://riscv-steel.github.io/riscv-steel-core/ recently and I did not update OpenCores. I will do that now. Thanks!

**Comment by hassanraza-10x** [comment]
This document https://riscv-steel.github.io/riscv-steel-core/ does not show the implementation details as mentioned in that webpage.

**Comment by rafaelcalcada** [comment]
Sorry for that, I'm writing new docs because the microarchitecture changed a lot recently. I will take some time to update everything.

**Comment by hassanraza-10x** [comment]
No problem, but can you provide me with any top level block diagram image of this core that shows how many stages have been implementated? An old one will also work

**Comment by rafaelcalcada** [comment]
Of course. Below is an old image but it is pretty close to what the core actually is now:

![image](https://github.com/riscv-steel/riscv-steel-core/assets/22325319/8a8428cf-e9e3-4d7a-93a3-eee374400977)

**Comment by hassanraza-10x** [comment]
Thank you
