### ISSUE TITLE
Test compilation instructions

### ISSUE THREAD

**Issue by Aidan-McNay** [riscv-steel/riscv-steel-core#8]
@riscv-steel I'm a bit confused by how the testing framework is meant to be compiled. It points to a testing framework repo, but doesn't give clear instructions how to reproduce. Could there be step-by-step commands on how to compile and test the design from a clean clone (looking to hopefully automate testing with GitHub Actions on push :) )

**Comment by rafaelcalcada** [comment]
Hi Aidan, thanks for your question. To run the unit tests you need to execute the testbench in **tb_riscv_steel_core.v**. I usually execute it in Vivado simulator (XSim), though other simulation tools can be used. To make it easier for you I uploaded a Vivado project to run the testbench in Vivado. It's available at **tests/vivado/riscv-arch-test.xpr**. You just need to open it with Vivado and hit "Run simulation".

You can download the free version of Vivado at https://www.xilinx.com/support/download.html. 

The unit test programs do not need to be recompiled as they will always be the same. The instructions to compile these unit test programs are indeed not very clear, and you find them in the v2.0 branch of https://github.com/riscv-non-isa/riscv-arch-test.

The version of the test framework I'm using (2.0) will be soon discontinued. It was the current version at the time I first wrote the testbench. I am updating to RISCOF framework (v3.0) and will write new docs when I finish RISCOF migration.

**Comment by Aidan-McNay** [comment]
Perfect - thanks a lot!
